apiVersion: apps/v1
kind: Deployment

metadata:
  name: capstone
  region: us-west-2
  labels:
    app: capstone
    type: restapi
  namespace: default

spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: capstone-project-template
    spec:
      containers:
        - image: adegokem/capstone:latest
          imagePullPolicy: Always
          name: capstone-project
          ports:
            - containerPort: 80
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-svc
  namaspace: capstone-svc
  labels:
    app: capstone
spec:
  type: eks-deployment
  selector:
    app: capstone
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP