apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-capstone
  labels:
    app: udacity-capstone
    type: restapi
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-capstone
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: udacity-capstone-template
    spec:
      containers:
        - image: adegokem/capstone:latest
          imagePullPolicy: Always
          name: udacity-capstone
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: udacity-capstone-svc
  labels:
    app: udacity-capstone
spec:
  type: LoadBalancer
  selector:
    app: udacity-capstone
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP