apiVersion: apps/v1
kind: Deployment

metadata:
  name: capstone
  labels:
    app: capstone
  namespace: default

spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - image: adegokem/capstone
          imagePullPolicy: Always
          name: capstone
          ports:
            - containerPort: 80
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64

---
apiVersion: v1
kind: Service

metadata:
  name: capstone
  labels:
    app: capstone
  namespace: default

spec:
  type: LoadBalancer
  selector:
    app: capstone
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP