---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-linux-deployment
  namespace: capstone
  labels:
    app: capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - image: adegokem/capstone
          imagePullPolicy: IfNotPresent
          name: capstone
          ports:
            - containerPort: 80
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-linux-service
  labels:
    app: capstone
  namespace: capstone
spec:
  selector:
    app: capstone
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP